---
title: "Biogeoclimatic Ecosystem Classification"
output:
  html_document:
    code_folding: hide
    css: veg_report.css
    
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(ggplot2)
require(RColorBrewer)
require(kableExtra)
require(data.table)
library(stringr)
library(ggraph)
library(igraph)
library(tidyverse)
library(rgdal)
library(broom)
library(ggplot2)
library("rjson")

```


```{r, echo=FALSE}
level_name <- "Order"
level_value <- "ORDER Poputre"
```

### Site Units
```{r choose site unit, echo=FALSE}
hier_summary <- readRDS(file.path("../level", level_name, level_value, "heir_summary_ORDER_Poputre.RDS"))
site_units <- hier_summary$SiteUnits
print(site_units)
```

### Plot Numbers with Site Units
```{r, echo=FALSE}
site_unit <- site_units[[2]]

SUTab <- fread("../BEC_ReportR/Classification_tables/ALLBECSU_2021_SU.csv")

plot_numbers_with_site_unit <- SUTab$PlotNumber[SUTab$SiteUnit == site_unit]
print(plot_numbers_with_site_unit)

```
<div class="header">
  <span class="emphasized">`r level_name` `r level_value` </span>
  <span class="emphasized">`r site_unit` </span>
</div>



```{r, echo=FALSE}
reports_dir <- "veg_reports"
csv_file_path <- function(layer_name, site_unit) file.path(reports_dir, paste(layer_name, str_replace(str_remove_all(site_unit, " "), "/", "_"), ".csv", sep="_"))


df_herb <- read.csv(file = file.path('../level', level_name, level_value, csv_file_path("Herb_Layer", site_unit)))
df_moss <- read.csv(file = file.path('../level', level_name, level_value, csv_file_path("Moss_Layer", site_unit)))
df_shrub <- read.csv(file = file.path('../level', level_name, level_value, csv_file_path("Shrub_Layer", site_unit)))
df_tree <- read.csv(file = file.path('../level', level_name, level_value, csv_file_path("Tree_Layer", site_unit)))

len_herb <- nrow(df_herb)
len_moss <- nrow(df_moss)
len_shrub <- nrow(df_shrub)
len_tree <- nrow(df_tree)

```

```{r Join data, echo=FALSE}
df <- rbind(df_tree, df_shrub, df_herb, df_moss)
```


```{r Veg report, echo=FALSE}
df <- df[, c("Layer","ScientificName", "constantcy","meanCover","EnglishName")]

kbl(df, col.names = c("Layer", "Scientific Name", "Constantcy", "Mean Cover", "English Name"), format = "html", table.attr = "style='width:100%;'", align = "lllll") %>%
  kable_styling() %>%
  row_spec(0, extra_css = "border-bottom: 1px solid") %>%
  row_spec(len_tree, extra_css = "border-bottom: 1px solid") %>%
  row_spec(len_tree + len_shrub, extra_css = "border-bottom: 1px solid") %>%
  row_spec(len_tree + len_shrub + len_herb, extra_css = "border-bottom: 1px solid")
```
# Edatopic Grid

```{r Get soil moisture regime, echo=FALSE}
env_summary <- fromJSON(file=file.path("../level", level_name, level_value, "summaries", "env", paste(str_replace_all(level_value, " ", "_"), ".JSON",  sep="")))

soil_moisture_regime <- env_summary$MoistureRegime
soil_moisture_regime_values <- as.numeric(names(soil_moisture_regime$summary))

soil_moisture_regime_values <- soil_moisture_regime_values[!is.na(soil_moisture_regime_values)]

y_range <- range(soil_moisture_regime_values)

y_1 <- y_range[1]
y_2 <- y_range[2]

```
```{r Get aSMR data, echo=FALSE}
  
aSMR_Plot_data_for_level <- read.csv(file=file.path("../level", level_name, level_value,"aSMR_Plot_data_for_level.csv"))
asmr <- aSMR_Plot_data_for_level$aSMR
asmr <- asmr[!is.na(asmr)]
x_range <- range(asmr)

x_1 <- x_range[1]
x_2 <- x_range[2]
```


```{r, echo=FALSE}
library("ggplot2")

df=data.frame(x1=c(x_1), x2=c(x_2), y1=c(y_1), y2=c(y_2), colour=c('green'), r=c(1))
x_lab = c("v.           \npoor            ", "poor            ", "medium            ", "rich            ", "v.            \nrich            ")
y_lab = c("very wet", "wet", "very moist", "moist", "fresh", "slightly dry", "moderely dry", "very dry", "extremely dry", "excessively dry")

ggplot() + 
scale_x_continuous(name="Soil Nutrient Regime", labels=x_lab, limits=c(0,5), breaks=c(1,2,3,4,5), expand = c(0, 0), position = "top") + 
scale_y_continuous(name="actual Soil Moisture Regime", labels=y_lab, limits=c(0,10), breaks=c(1,2,3,4,5,6,7,8,9,10), expand=c(0, 0)) +
coord_fixed() +
geom_rect(data=df, mapping=aes(xmin=x1, xmax=x2, ymin=y1, ymax=y2), fill=df$colour, color="black", alpha=0.5) +
geom_text(data=df, aes(x=x1+(x2-x1)/2, y=y1+(y2-y1)/2, label=r), size=4) + 
theme(
  panel.grid.major = element_line(linetype = 2, color="#A7A7A7", size = 0.3),
  panel.grid.minor.x = element_blank(),
  panel.grid.minor.y = element_blank(),
  panel.border = element_rect(colour = "black", size=1, fill=NA),
  panel.background = element_rect(fill="#F2F2F2"),
  axis.ticks.x = element_blank(),
  axis.ticks.y = element_blank(),
  axis.ticks = element_blank(),
  axis.text.x = element_text(face="bold", size=10),
  axis.text.y = element_text(face="bold", size=10, vjust=2.75),
  axis.title = element_text(face="bold") 
 )
```

```{r, echo=FALSE}

level_names <- c("Classes", "Orders", "SubOrder", "Alliannces", "Associations")
level_labels <- unlist(c(hier_summary$Classes, hier_summary$Orders, hier_summary$SubOrder, hier_summary$Alliances, hier_summary$Associations)) 
level_labels <- level_labels[!is.na(level_labels)]

d1 <- data.frame(from=hier_summary$Classes, to=hier_summary$Orders)
d2 <- data.frame(from=d1$to, to=hier_summary$SubOrder)
d3 <- data.frame(from=d2$to, to=hier_summary$Alliances)
d4 <- data.frame(from=d3$to, to=hier_summary$Associations)
edges <- drop_na(rbind(d1, d2, d3, d4))

 
# Create a graph object 
mygraph <- graph_from_data_frame( edges )
 
# Basic tree
ggraph(mygraph, layout = 'dendrogram', circular = FALSE) + 
  geom_edge_diagonal() +
  geom_node_point() +
  geom_node_label(aes(label = level_labels), repel = TRUE) +
  theme_void()
```

```{r, echo=FALSE}
my_spdf <- readOGR(dsn= paste0("../BEC_ReportR/Spatial_files"), verbose=FALSE)
```
## Map

```{r, echo=FALSE}
spdf_fortified <- tidy(my_spdf)

# Plot it
library(ggplot2)
ggplot() +
  geom_polygon(data = spdf_fortified, aes( x = long, y = lat, group = group), fill="#69b3a2", color="white") +
  theme_void() 
```

## Strata cover

```{r}
# strata_cover_tree <- env_summary$StrataCoverTree
# strata_cover_hurb <- env_summary$StrataCoverTree

ENV_Plot_data_for_level <- read.csv(file=file.path("../level", level_name, level_value,"ENV_Plot_data_for_level.csv"))
strata_cover_tree <- ENV_Plot_data_for_level$StrataCoverTree
#asmr <- asmr[!is.na(asmr)]

```

```{r}

```


## Grouped Violin Plots
```{r}
p <- ggplot(ENV_Plot_data_for_level, aes(StrataCoverTree, "Tree")) +
  geom_violin() +
  geom_boxplot(width = .1) +
  coord_flip()

q <- ggplot(ENV_Plot_data_for_level, aes(StrataCoverHerb, "Herb")) +
  geom_violin() +
  geom_boxplot(width = .1) +
  coord_flip()

r <- ggplot(ENV_Plot_data_for_level, aes(StrataCoverShrub, "Shrub")) +
  geom_violin() +
  geom_boxplot(width = .1) +
  coord_flip()

s <- ggplot(ENV_Plot_data_for_level, aes(StrataCoverMoss, "Moss")) +
  geom_violin() +
  geom_boxplot(width = .1) +
  coord_flip()

p
q
r
s

```


```{r}
p <- ggplot(mtcars, aes(factor(cyl), mpg)) +
  geom_violin() +
  geom_boxplot(width = .1)

p
```

## Box Plots

```{r}
# A really basic boxplot.
ggplot(mtcars, aes(x=as.factor(cyl), y=mpg)) + 
    coord_flip() +
    geom_boxplot( alpha=0.2) +    # fill="slateblue"
    xlab("cyl") 
```

## Wind Rose

```{r, echo=FALSE}
# WindRose.R
plot.windrose <- function(data,
                      spd,
                      dir,
                      spdres = 2,
                      dirres = 30,
                      spdmin = 2,
                      spdmax = 20,
                      spdseq = NULL,
                      palette = "YlGnBu",
                      countmax = NA,
                      debug = 0) {


# Look to see what data was passed in to the function
  if (is.numeric(spd) & is.numeric(dir)){
    # assume that we've been given vectors of the speed and direction vectors
    data <- data.frame(spd = spd,
                       dir = dir)
    spd = "spd"
    dir = "dir"
  } else if (exists("data")){
    # Assume that we've been given a data frame, and the name of the speed 
    # and direction columns. This is the format we want for later use.    
  }  

  # Tidy up input data ----
  n.in <- NROW(data)
  dnu <- (is.na(data[[spd]]) | is.na(data[[dir]]))
  data[[spd]][dnu] <- NA
  data[[dir]][dnu] <- NA

  # figure out the wind speed bins ----
  if (missing(spdseq)){
    spdseq <- seq(spdmin,spdmax,spdres)
  } else {
    if (debug >0){
      cat("Using custom speed bins \n")
    }
  }
  # get some information about the number of bins, etc.
  n.spd.seq <- length(spdseq)
  n.colors.in.range <- n.spd.seq - 1

  # create the color map
  spd.colors <- colorRampPalette(brewer.pal(min(max(3,
                                                    n.colors.in.range),
                                                min(9,
                                                    n.colors.in.range)),                                               
                                            palette))(n.colors.in.range)

  if (max(data[[spd]],na.rm = TRUE) > spdmax){    
    spd.breaks <- c(spdseq,
                    max(data[[spd]],na.rm = TRUE))
    spd.labels <- c(paste(c(spdseq[1:n.spd.seq-1]),
                          '-',
                          c(spdseq[2:n.spd.seq])),
                    paste(spdmax,
                          "-",
                          max(data[[spd]],na.rm = TRUE)))
    spd.colors <- c(spd.colors, "grey50")
  } else{
    spd.breaks <- spdseq
    spd.labels <- paste(c(spdseq[1:n.spd.seq-1]),
                        '-',
                        c(spdseq[2:n.spd.seq]))    
  }
  data$spd.binned <- cut(x = data[[spd]],
                         breaks = spd.breaks,
                         labels = spd.labels,
                         ordered_result = TRUE)
  # clean up the data
  data. <- na.omit(data)

  # figure out the wind direction bins
  dir.breaks <- c(-dirres/2,
                  seq(dirres/2, 360-dirres/2, by = dirres),
                  360+dirres/2)  
  dir.labels <- c(paste(360-dirres/2,"-",dirres/2),
                  paste(seq(dirres/2, 360-3*dirres/2, by = dirres),
                        "-",
                        seq(3*dirres/2, 360-dirres/2, by = dirres)),
                  paste(360-dirres/2,"-",dirres/2))
  # assign each wind direction to a bin
  dir.binned <- cut(data[[dir]],
                    breaks = dir.breaks,
                    ordered_result = TRUE)
  levels(dir.binned) <- dir.labels
  data$dir.binned <- dir.binned

  # Run debug if required ----
  if (debug>0){    
    cat(dir.breaks,"\n")
    cat(dir.labels,"\n")
    cat(levels(dir.binned),"\n")       
  }  

  # deal with change in ordering introduced somewhere around version 2.2
  if(packageVersion("ggplot2") > "2.2"){    
    #cat("Hadley broke my code\n")
    data$spd.binned = with(data, factor(spd.binned, levels = rev(levels(spd.binned))))
    spd.colors = rev(spd.colors)
  }

  # create the plot ----
  p.windrose <- ggplot(data = data,
                       aes(x = dir.binned,
                           fill = spd.binned)) +
    geom_bar() + 
    scale_x_discrete(drop = FALSE,
                     labels = waiver()) +
    coord_polar(start = -((dirres/2)/360) * 2*pi) +
    scale_fill_manual(name = "Wind Speed (m/s)", 
                      values = spd.colors,
                      drop = FALSE) +
    theme(axis.title.x = element_blank())

  # adjust axes if required
  if (!is.na(countmax)){
    p.windrose <- p.windrose +
      ylim(c(0,countmax))
  }

  # print the plot
  print(p.windrose)  

  # return the handle to the wind rose
  return(p.windrose)
}


```

```{r, echo=FALSE}
data.in <- read.csv(file = "wind_data.csv", col.names = c("date","hr","ws.80","wd.80"))

p1 <- plot.windrose(spd = data.in$ws.80,
                   dir = data.in$wd.80)


```


