---
title: "R Notebook"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

require(tidyverse)
require(tidymodels)
require(data.table)
require(data.tree)
require(DataExplorer)
require(C50)
require(indicspecies)
require(doParallel)
require(philentropy)
require(dplyr)
```

```{r}
source("CodeUsingTreeFunctions.R")
```


```{r}
source("./_functions/_TabletoTree.R")
source("./_functions/_TreetoTable.R")
source("./_functions/_VegdatSUsummary.R") 
source("./_functions/_spp_importance.R")
source("./_functions/_CreateHierReportData.R")
```

```{r Create Hier Report and produce plot numbers in level}

# Need to do for each level for each level_value in level
level_name <- "Order"
level_value <- "ORDER Poputre"

unique_classes <- unique(Hier.data[["Class"]])
unique_orders <- unique(Hier.data[["Order"]])
unique_suborder <- unique(Hier.data[["Suborder"]])
unique_alliance <- unique(Hier.data[["Alliance"]])
unique_assoc <- unique(Hier.data[["Assoc"]])


createHierReportData(level_name, level_value, SUTab)


#lapply(uniqueClasses, createReportData(levelName))

```



```{r Plot data sets}
ENV_Plot_data <- fread("./BEC_ReportR/Plot_Data/BECMaster19_ENV.csv")
Humus_Plot_data <- fread("./BEC_ReportR/Plot_Data/BECMaster19_Humus.csv")
Mineral_Plot_data <- fread("./BEC_ReportR/Plot_Data/BECMaster19_Mineral.csv")
Climate_Plot_data <- fread("./BEC_ReportR/Plot_Data/BECMaster_Plot_Climatedata.csv")
Admin_Plot_data <- fread("./BEC_ReportR/Plot_Data/BECMaster19_Admin.csv")
```


```{r}
# Get plot_numbers_in_level
plot_numbers_file_name <- paste("plot_numbers_in_", str_replace_all(level_value, " ", "_"), ".RDS", sep="")
plot_numbers_in_level <- readRDS(file.path("plotNumbers", level_name, plot_numbers_file_name))[[1]]


# Get relevant plot data rows from each Plot data file

#ENV_Plot_data_for_level <- ENV_Plot_data %>% filter(ENV_Plot_data$PlotNumber %in% plot_numbers_in_level)


ENV_Plot_data_for_level <- ENV_Plot_data[ENV_Plot_data$PlotNumber %in% plot_numbers_in_level]
Humus_Plot_data_for_level <- Humus_Plot_data[Humus_Plot_data$PlotNumber %in% plot_numbers_in_level]
Mineral_Plot_data_for_level <- Mineral_Plot_data[Mineral_Plot_data$PlotNumber %in% plot_numbers_in_level]
Climate_Plot_data_for_level <-  Climate_Plot_data[Climate_Plot_data$PlotNumber %in% plot_numbers_in_level]
Admin_Plot_data_for_level <- Admin_Plot_data[Admin_Plot_data$PlotNumber %in% plot_numbers_in_level]
  
# Write relevant plot data rows from each Plot
```



```{r Create empty lookup function json files for each plot file }

#reports_dir <- file.path("reports", level_name) 
#if (!dir.exists(reports_dir)) dir.create(reports_dir, recursive = TRUE)

library(rjson)

create_json_template <- function(plot_data_names, file_name) {
  
  if (!dir.exists("lookup_functions")) {
    dir.create("lookup_functions")
  }
  
  if(file.exists(file.path("lookup_functions", file_name))) return()
  
  names_list <- list()
  for (name in plot_data_names) {
    names_list[[ name ]] <- list(variableType="")
  }
  write(toJSON(names_list), file.path("lookup_functions", file_name))
}


create_json_template(names(ENV_Plot_data), "env_lookup_functions.json")
create_json_template(names(Humus_Plot_data), "humus_lookup_functions.json")
create_json_template(names(Mineral_Plot_data), "mineral_lookup_functions.json")
create_json_template(names(Climate_Plot_data), "climate_lookup_functions.json")
create_json_template(names(Admin_Plot_data), "admin_lookup_functions.json")

# Note: The functions need to be manually filled out in the json file

```


```{r Read lookup functions}
env_lookup_functions <- fromJSON(file="lookup_functions/env_lookup_functions.json")
humus_lookup_functions <- fromJSON(file="lookup_functions/env_lookup_functions.json")
mineral_lookup_functions <- fromJSON(file="lookup_functions/env_lookup_functions.json")
climate_lookup_functions <- fromJSON(file="lookup_functions/env_lookup_functions.json")
admin_lookup_functions <- fromJSON(file="lookup_functions/env_lookup_functions.json")
```

```{r Function to clean list data}


clean_list_element <- function(element) {
  items <- as.list(trimws(el(strsplit(element, "/|,|;|-|\\+| AND | and |&|,"))))
  return (items)
}

clean_list_data <- function(df_column) {
  l <- unlist(lapply(df_column, function(element) clean_list_element(element)))
  return(l)
}

print(clean_list_data(c("O. Kanji, J. Doe", "A,B , C, D/E", "X/Y/Z", "z+x+y")))

# coordinate - heat map of locations or mode
# quantitiative - summary
# catagorical - table


```


```{r Roll up functions into pre report summaries}
roll_up_plot_data <- function(plot_data, lookup_function_list) {

  variable_summaries <- list()
  
  for (variable_name in names(lookup_function_list)) {
      
    
    variable_type <- lookup_function_list[[variable_name]]$variableType
    is_list <- lookup_function_list[[variable_name]]$isList
    
    #data <- list(plot_data[[variable_name]])
    
    if(!is.null(is_list) && is_list) {
      data <- clean_list_data(plot_data[[variable_name]])
    } else {
      data <- trimws(plot_data[[variable_name]])
                     
    }
 
    data <- data[!is.null(data)]
    data <- data[data != ""]
    data <- data[!is.na(data)]
  
    if(variable_type == "categorical") {
      variable_summaries[[variable_name]] <- list(variable_type=variable_type, summary=table(data))
    } else if(variable_type == "quantitative") {
      variable_summaries[[variable_name]] <- list(variable_type=variable_type, summary=summary(as.numeric(data)))
    } else if(variable_type == "coordinate") {
      variable_summaries[[variable_name]] <- list(variable_type=variable_type, summary=unique(data))
    } else if(variable_type == "description"){
      variable_summaries[[variable_name]] <- list(variable_type=variable_type, summary=data)
    }



    #variable_summaries[[function_name]] <- list(do.call(function_name, list(plot_data[[variable_name]])))
    
    
  }
  
  return(variable_summaries)
}

env_summary <- roll_up_plot_data(ENV_Plot_data_for_level, env_lookup_functions)
#print(env_summary)
json_env_summary <- toJSON(env_summary)
write(json_env_summary, "./summaries/json_env_summary.json")
# humas_summary <- roll_up_plot_data(Humus_Plot_data_for_level, humus_lookup_functions)
# mineral_summary <- roll_up_plot_data(Mineral_Plot_data_for_level, mineral_lookup_functions)
# climate_summary <- roll_up_plot_data(Climate_Plot_data_for_level, climate_lookup_functions)
# admin_summary <- roll_up_plot_data(Admin_Plot_data_for_level, admin_lookup_functions)
```

