---
title: "Biogeoclimatic Ecosystem Classification"
output:
  html_document:
    code_folding: hide
    css: veg_report.css
    
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(kableExtra)
require(data.table)
library(stringr)
library(ggraph)
library(igraph)
library(tidyverse)
library(rgdal)
library(broom)
```


```{r, echo=FALSE}
level_name <- "Order"
level_value <- "ORDER Poputre"
```

### Site Units
```{r choose site unit, echo=FALSE}
hier_summary <- readRDS(file.path("../level", level_name, level_value, "heir_summary_ORDER_Poputre.RDS"))
site_units <- hier_summary$SiteUnits
print(site_units)
```

### Plot Numbers with Site Units
```{r, echo=FALSE}
site_unit <- site_units[[2]]

SUTab <- fread("../BEC_ReportR/Classification_tables/ALLBECSU_2021_SU.csv")

plot_numbers_with_site_unit <- SUTab$PlotNumber[SUTab$SiteUnit == site_unit]
print(plot_numbers_with_site_unit)

```
<div class="header">
  <span class="emphasized">`r level_name` `r level_value` </span>
  <span class="emphasized">`r site_unit` </span>
</div>



```{r, echo=FALSE}
reports_dir <- "veg_reports"
csv_file_path <- function(layer_name, site_unit) file.path(reports_dir, paste(layer_name, str_replace(str_remove_all(site_unit, " "), "/", "_"), ".csv", sep="_"))


df_herb <- read.csv(file = file.path('../level', level_name, level_value, csv_file_path("Herb_Layer", site_unit)))
df_moss <- read.csv(file = file.path('../level', level_name, level_value, csv_file_path("Moss_Layer", site_unit)))
df_shrub <- read.csv(file = file.path('../level', level_name, level_value, csv_file_path("Shrub_Layer", site_unit)))
df_tree <- read.csv(file = file.path('../level', level_name, level_value, csv_file_path("Tree_Layer", site_unit)))

len_herb <- nrow(df_herb)
len_moss <- nrow(df_moss)
len_shrub <- nrow(df_shrub)
len_tree <- nrow(df_tree)

```

```{r Join data, echo=FALSE}
df <- rbind(df_tree, df_shrub, df_herb, df_moss)
```


```{r Veg report, echo=FALSE}
df <- df[, c("Layer","ScientificName", "constantcy","meanCover","EnglishName")]

kbl(df, col.names = c("Layer", "Scientific Name", "Constantcy", "Mean Cover", "English Name"), format = "html", table.attr = "style='width:100%;'", align = "lllll") %>%
  kable_styling() %>%
  row_spec(0, extra_css = "border-bottom: 1px solid") %>%
  row_spec(len_tree, extra_css = "border-bottom: 1px solid") %>%
  row_spec(len_tree + len_shrub, extra_css = "border-bottom: 1px solid") %>%
  row_spec(len_tree + len_shrub + len_herb, extra_css = "border-bottom: 1px solid")
```
# Edatopic Grid
```{r, echo=FALSE}
library("ggplot2")

df=data.frame(x1=c(1), x2=c(3.5), y1=c(5), y2=c(2), colour=c('green'), r=c(1))
x_lab = c("v.           \npoor            ", "poor            ", "medium            ", "rich            ", "v.            \nrich            ")
y_lab = c("very wet", "wet", "very moist", "moist", "fresh", "slightly dry", "moderely dry", "very dry", "extremely dry", "excessively dry")

ggplot() + 
scale_x_continuous(name="Soil Nutrient Regime", labels=x_lab, limits=c(0,5), breaks=c(1,2,3,4,5), expand = c(0, 0), position = "top") + 
scale_y_continuous(name="actual Soil Moisture Regime", labels=y_lab, limits=c(0,10), breaks=c(1,2,3,4,5,6,7,8,9,10), expand=c(0, 0)) +
coord_fixed() +
geom_rect(data=df, mapping=aes(xmin=x1, xmax=x2, ymin=y1, ymax=y2), fill=df$colour, color="black", alpha=0.5) +
geom_text(data=df, aes(x=x1+(x2-x1)/2, y=y1+(y2-y1)/2, label=r), size=4) + 
theme(
  panel.grid.major = element_line(linetype = 2, color="#A7A7A7", size = 0.3),
  panel.grid.minor.x = element_blank(),
  panel.grid.minor.y = element_blank(),
  panel.border = element_rect(colour = "black", size=1, fill=NA),
  panel.background = element_rect(fill="#F2F2F2"),
  axis.ticks.x = element_blank(),
  axis.ticks.y = element_blank(),
  axis.ticks = element_blank(),
  axis.text.x = element_text(face="bold", size=10),
  axis.text.y = element_text(face="bold", size=10, vjust=2.75),
  axis.title = element_text(face="bold") 
 )
```

```{r, echo=FALSE}

level_names <- c("Classes", "Orders", "SubOrder", "Alliannces", "Associations")
level_labels <- unlist(c(hier_summary$Classes, hier_summary$Orders, hier_summary$SubOrder, hier_summary$Alliances, hier_summary$Associations)) 
level_labels <- level_labels[!is.na(level_labels)]

d1 <- data.frame(from=hier_summary$Classes, to=hier_summary$Orders)
d2 <- data.frame(from=d1$to, to=hier_summary$SubOrder)
d3 <- data.frame(from=d2$to, to=hier_summary$Alliances)
d4 <- data.frame(from=d3$to, to=hier_summary$Associations)
edges <- drop_na(rbind(d1, d2, d3, d4))

 
# Create a graph object 
mygraph <- graph_from_data_frame( edges )
 
# Basic tree
ggraph(mygraph, layout = 'dendrogram', circular = FALSE) + 
  geom_edge_diagonal() +
  geom_node_point() +
  geom_node_label(aes(label = level_labels), repel = TRUE) +
  theme_void()
```

```{r, echo=FALSE}
my_spdf <- readOGR(dsn= paste0("../BEC_ReportR/Spatial_files"), verbose=FALSE)
```
## Map

```{r, echo=FALSE}
spdf_fortified <- tidy(my_spdf)

# Plot it
library(ggplot2)
ggplot() +
  geom_polygon(data = spdf_fortified, aes( x = long, y = lat, group = group), fill="#69b3a2", color="white") +
  theme_void() 
```

